- name: Trigger GitHub Actions workflow
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ repo_owner }}/{{ repo_name }}/actions/workflows/{{ workflow_file | basename }}/dispatches"
    method: POST
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ github_token }}"
    body_format: json
    body:
      ref: "{{ branch_name }}"
      inputs: "{{ inputs }}"
    status_code: 204
  register: result

- name: Show result
  ansible.builtin.debug:
    var: result
